sources:
  weather:
    format: json
    gcs_path: gs://open_meteo_weather_data_dm2/*.json
    big_query_table: guess_my_mood_dataset.stg_weather_data
    json_path: open_meteo_weather_data.json
    api_url: https://historical-forecast-api.open-meteo.com/v1/forecast
    bucket: open_meteo_weather_data_dm2
    latitude: 49.3988
    longitude: 8.6724 
    timezone: Europe/Berlin

  music:
    format: json
    gcs_path: gs://last_fm_music_data_dm2/*.json
    big_query_table: guess_my_mood_dataset.stg_music_data
    bucket: last_fm_music_data_dm2
    api_url: https://ws.audioscrobbler.com/2.0/
    json_path: last_fm_music_data.json